### ISSUE TITLE
Error on CentOS 6.7 with git credential manager 2.0.2

### ISSUE THREAD

**Issue by eqbalz** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#62]
I installed this on CentOS following the instructions. But unable to get it to work. I get no pop-up window to login with 2FA. When running with debug I get the following errors when running in a shell terminal with X Window Server running:

```
Program::ComponentFactory::createSecureStore
gnome-keyring library loaded, creating a password SCHEMA
Could not get default keyring info. GNOME Keyring is not available.
Return code: 2 description: The gnome-keyring-daemon application is not running.
Getting a persistent token store that must be secure
Getting a persistent credential store that must be secure
Fatal error encountered.  Details:
java.lang.IllegalArgumentException: tokenSecretStore can't be null
        at com.microsoft.alm.authentication.SecretStoreAdapter.<init>(SecretStoreAdapter.java:17)
        at com.microsoft.alm.gitcredentialmanager.Program$ComponentFactory.createSecureStore(Program.java:1192)
        at com.microsoft.alm.gitcredentialmanager.Program.initialize(Program.java:882)
        at com.microsoft.alm.gitcredentialmanager.Program.get(Program.java:292)
        at com.microsoft.alm.gitcredentialmanager.Program.access$200(Program.java:63)
        at com.microsoft.alm.gitcredentialmanager.Program$3.call(Program.java:284)
        at com.microsoft.alm.gitcredentialmanager.Program$3.call(Program.java:281)
        at com.microsoft.alm.gitcredentialmanager.Program.innerMain(Program.java:195)
        at com.microsoft.alm.gitcredentialmanager.Program.main(Program.java:123)
fatal: credential helper '!/usr/java/jdk1.8.0_92/jre/bin/java -Ddebug=true -Djava.net.useSystemProxies=true -jar /usr/lib/git-credential-manager-2.0.2.jar' told us to qui
t
```
Strangely enough I get a different error when running inside a GUI terminal (with xrdp):

```
Program::ComponentFactory::createSecureStore
gnome-keyring library loaded, creating a password SCHEMA
Try access gnome-keyring with dummy data to make sure it's accessible...
Keyring is locked, most likely due to UI is unavailable or user logged in automatically without supplying a password.
Keyring is locked and unavailable, please set variable AUTH_LIB_ALLOW_UNLOCK_GNOME_KEYRING to allow unlocking the keyring with a popup dialog.
Getting a persistent token store that must be secure
Getting a persistent credential store that must be secure
Fatal error encountered.  Details:
java.lang.IllegalArgumentException: tokenSecretStore can't be null
        at com.microsoft.alm.authentication.SecretStoreAdapter.<init>(SecretStoreAdapter.java:17)
        at com.microsoft.alm.gitcredentialmanager.Program$ComponentFactory.createSecureStore(Program.java:1192)
        at com.microsoft.alm.gitcredentialmanager.Program.initialize(Program.java:882)
        at com.microsoft.alm.gitcredentialmanager.Program.get(Program.java:292)
        at com.microsoft.alm.gitcredentialmanager.Program.access$200(Program.java:63)
        at com.microsoft.alm.gitcredentialmanager.Program$3.call(Program.java:284)
        at com.microsoft.alm.gitcredentialmanager.Program$3.call(Program.java:281)
        at com.microsoft.alm.gitcredentialmanager.Program.innerMain(Program.java:195)
        at com.microsoft.alm.gitcredentialmanager.Program.main(Program.java:123)
fatal: credential helper '!/usr/java/jdk1.8.0_92/jre/bin/java -Ddebug=true -Djava.net.useSystemProxies=true -jar /usr/lib/git-credential-manager-2.0.2.jar' told us to qui
t
```
Not sure what is going on.

**Comment by yacaovsnc** [comment]
The credential manager tries to save the generated Personal Access Token (PAT) to a secure place, and on Linux we try to save the PAT to the "login" keyring of Gnome Keyring.  

Gnome keyring isn't accessible if you connect via ssh.  That's the first error you see.  

Also if the login keyring is locked, we won't be able to access it.  If you login without passwords, the login keyring maybe still locked.  Could you please set the environment variable suggested _AUTH_LIB_ALLOW_UNLOCK_GNOME_KEYRING_ to true and try again?  

Thanks.

**Comment by yacaovsnc** [comment]
If you still can't unlock gnome-keyring, you could try this option:
`git config --global credential.canFallBackToInsecureStore true`

If this is set, it will fallback to use insecure files to store your credential.  The generated file is at:
~/.VSTeamServicesAuthPlugin/insecureStore.xml

Closing for inactivity.
