### ISSUE TITLE
Implicit java.xml.bind dependency unsatisfied on Java 9

### ISSUE THREAD

**Issue by jamesottaway** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#71]
I installed Java via `brew cask install java` which gave me Java 9.

When I tried to clone a VSTS repo it failed, and I found the following stacktrace when running GCM4ML in debug mode:

```
VsoAzureAuthority::validateCredentials
Fatal error encountered.  Details:
java.lang.Error:    unexpected error
	at com.microsoft.alm.authentication.VsoAzureAuthority.validateCredentials(VsoAzureAuthority.java:214)
	at com.microsoft.alm.authentication.BaseVsoAuthentication.validateCredentials(BaseVsoAuthentication.java:204)
	at com.microsoft.alm.gitcredentialmanager.Program.get(Program.java:322)
	at com.microsoft.alm.gitcredentialmanager.Program.get(Program.java:293)
	at com.microsoft.alm.gitcredentialmanager.Program.access$200(Program.java:63)
	at com.microsoft.alm.gitcredentialmanager.Program$3.call(Program.java:284)
	at com.microsoft.alm.gitcredentialmanager.Program$3.call(Program.java:281)
	at com.microsoft.alm.gitcredentialmanager.Program.innerMain(Program.java:195)
	at com.microsoft.alm.gitcredentialmanager.Program.main(Program.java:123)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.microsoft.alm.secret.Credential.contributeHeader(Credential.java:125)
	at com.microsoft.alm.authentication.VsoAzureAuthority.createConnectionDataRequest(VsoAzureAuthority.java:315)
	at com.microsoft.alm.authentication.VsoAzureAuthority.validateCredentials(VsoAzureAuthority.java:199)
	... 8 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 11 more
```

Turns out you need to specify the `--add-modules java.xml.bind` flag to include the `DatatypeConverter` class definition.

I'll leave it up to someone with more current Java experience than mine to find a proper solution to this which won't break people on Java 8…

**Comment by K4pt4n** [comment]
For an end user, is there something I can run to get this going? I assume this has to do with needing to turn on the insecure option.

**Comment by jamesottaway** [comment]
Follow the [manual installation instructions](https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/blob/master/Install.md#manual-configuration-1) but add `--add-modules java.xml.bind` to the command when you update the `credential.helper` config value.

**Comment by carlosvin** [comment]
@jamesottaway, thanks, that works for me: 
`[credential]
	helper = !/usr/lib/jvm/java-10-jdk/bin/java --add-modules java.xml.bind -Ddebug=false -Djava.net.useSystemProxies=true -jar /usr/share/java/git-credential-manager-2.0.3.jar
`

**Comment by praveeno** [comment]
it would be great if this `--add-modules java.xml.bind ` can add in README

**Comment by novak** [comment]
This issue should be resolved in the newly released version 2.0.4. There were a few changes made to support Java 9+.

Please let me know if you continue to see an issue.
